{
 "title": "LXC containers",
 "tags": [
  "lxc",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM lxcstats WITH KEY=host"
   },
   {
    "name": "lxc_host",
    "label": "Container",
    "query": "SHOW TAG VALUES FROM lxcstats WITH KEY=lxc_host WHERE \"host\"=~/$server/"
   },
   { "name": "interval", "query": "10s,30s,1m,5m" }
  ]
 },
 "panels": [
  { "title": "$lxc_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "lxc_host" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "cpu %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "query": "SELECT (non_negative_derivative(last(\"cpu_time\"), 1s) / 1000000000) FROM \"lxcstats\" WHERE (\"host\" =~ /^$server$/ AND \"lxc_host\" =~ /^$lxc_host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    },
    {
     "alias": "limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "select": [
      [
       { "params": [ "cpu_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "select": [
      [
       { "params": [ "mem_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    },
    {
     "alias": "memory limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "select": [
      [
       { "params": [ "mem_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "read bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "select": [
      [
       { "params": [ "blkio_read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    },
    {
     "alias": "write bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "query": "SELECT non_negative_difference(mean(\"blkio_write_bytes\")) FROM \"lxcstats\" WHERE (\"host\" =~ /^$server$/ AND \"lxc_host\" =~ /^$lxc_host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "blkio_write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "out bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "query": "SELECT non_negative_difference(mean(\"bytes_sent\")) FROM \"lxcstats\" WHERE (\"host\" =~ /^$server$/ AND \"lxc_host\" =~ /^$lxc_host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    },
    {
     "alias": "in bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lxcstats",
     "query": "SELECT non_negative_difference(mean(\"bytes_sent\")) FROM \"lxcstats\" WHERE (\"host\" =~ /^$server$/ AND \"lxc_host\" =~ /^$lxc_host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "lxc_host", "operator": "=~", "value": "/^$lxc_host$/" }
     ]
    }
   ]
  }
 ]
}