{
 "title": "HAproxy stats",
 "description": "influxdb database template for haproxy english version",
 "tags": [
  "haproxy",
  "influxdb",
  "Pre-release"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "server",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"host\""
   },
   {
    "name": "proxy",
    "label": "service name",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "sv",
    "label": "application",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"sv\""
   }
  ]
 },
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http request per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT last(\"req_rate\") FROM \"haproxy\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "req_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sv", "operator": "=~", "value": "/^$sv$/" },
      { "condition": "AND", "key": "proxy", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "title": "create session number per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "request error number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sv", "operator": "=~", "value": "/^$sv$/" },
      { "condition": "AND", "key": "proxy", "operator": "=", "value": "main" }
     ]
    }
   ]
  },
  {
   "title": "session usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=", "value": "main" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT last(\"rtime\") * last(\"rsp_comp\")FROM \"haproxy\" WHERE (\"host\" =~ /^$host$/ AND \"proxy\" = 'wp' AND \"sv\" =~ /^$sv$/) AND $timeFilter GROUP BY time(1m), \"proxy\"",
     "select": [
      [
       { "params": [ "rtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=", "value": "wp" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "request to receive the number of errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "response refused number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "dresp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "response to the wrong request number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "eresp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  { "title": "Frontend_hrps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "http answer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1xx",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "http_response.1xx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "2xx",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "http_response.2xx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "3xx",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "http_response.3xx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "4xx",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "http_response.4xx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "5xx",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "http_response.5xx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  { "title": "Frontend_byte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "front_recv_byte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "bin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "front_sent_byte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "bout" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  { "title": "Backend_request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "backend_recv_byte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sv" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "bin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "backend_sent_byte",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sv" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "bout" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  }
 ]
}