{
 "title": "Nginx",
 "description": "Performance metrics for Nginx",
 "tags": [
  "Nginx",
  "InfluxDB",
  "Telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"nginx\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Nginx $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT percentile(\"request_time\" * 1000, 95) FROM \"nginx_access_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "P95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT percentile(\"request_time\" * 1000, 95) FROM \"nginx_access_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "P75",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT percentile(\"request_time\" * 1000, 95) FROM \"nginx_access_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT percentile(\"request_time\" * 1000, 95) FROM \"nginx_access_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT percentile(\"request_time\" * 1000, 95) FROM \"nginx_access_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_verb",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "verb" ], "type": "tag" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "client_ip" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Body Trafic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "HTTP 1xx",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^1/" }
     ]
    },
    {
     "alias": "HTTP  2xx",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT sum(\"resp_bytes\")  * 1s / $__interval FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/ AND \"resp_code\" =~ /^2/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^2/" }
     ]
    },
    {
     "alias": "HTTP  3xx",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^3/" }
     ]
    },
    {
     "alias": "HTTP  4xx",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^4/" }
     ]
    },
    {
     "alias": "HTTP  5xx",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "nginx_access_log",
     "query": "SELECT mean(\"resp_bytes\") FROM \"nginx_access_log\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"resp_code\" fill(null) SLIMIT 10",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "resp_code", "operator": "=~", "value": "/^5/" }
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "accepts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "accepts" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "handled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "handled" ], "type": "alias" }
      ],
      [
       { "params": [ "reading" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "reading" ], "type": "alias" }
      ],
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "requests" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "waiting" ], "type": "alias" }
      ],
      [
       { "params": [ "writing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "writing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}